/**
 * Canonical vendor master. Procurement, goods inward, QC rejections and
 * vendor returns all reference vendors by `id` from this list.
 */
export const VENDORS = [
  {
    id: "vnd-ultratech",
    code: "VND-0001",
    name: "UltraTech Building Solutions",
    type: "Manufacturer",
    gstNumber: "36AAACU1234F1Z5",
    address: "Plot 14, Industrial Area, Hyderabad, Telangana",
    contacts: [
      { name: "Rajesh Kumar", role: "Sales Manager", phone: "+919845012345", email: "rajesh.kumar@ultratech-example.com" },
    ],
    materialCategories: ["cement", "aggregate"],
    rating: 4.6,
    deliveryPerformance: 0.94,
    qualityAcceptanceRate: 0.98,
    rejectionRate: 0.02,
    priceCompetitiveness: "Competitive",
    status: "active",
  },
  {
    id: "vnd-jsw-steel",
    code: "VND-0002",
    name: "JSW Steel Distributors",
    type: "Manufacturer",
    gstNumber: "29AAACJ5678K1Z2",
    address: "Peenya Industrial Estate, Bengaluru, Karnataka",
    contacts: [
      { name: "Meera Shah", role: "Regional Head", phone: "+919845098765", email: "meera.shah@jswsteel-example.com" },
    ],
    materialCategories: ["steel"],
    rating: 4.8,
    deliveryPerformance: 0.9,
    qualityAcceptanceRate: 0.99,
    rejectionRate: 0.01,
    priceCompetitiveness: "Premium",
    status: "active",
  },
  {
    id: "vnd-shree-sand",
    code: "VND-0003",
    name: "Shree Sand & Aggregates Co.",
    type: "Supplier",
    gstNumber: "27AACFS9988L1ZH",
    address: "MIDC Road, Pune, Maharashtra",
    contacts: [
      { name: "Vikram Patil", role: "Proprietor", phone: "+919822011223", email: "vikram@shreesand-example.com" },
    ],
    materialCategories: ["sand", "aggregate", "bricks"],
    rating: 4.1,
    deliveryPerformance: 0.82,
    qualityAcceptanceRate: 0.93,
    rejectionRate: 0.07,
    priceCompetitiveness: "Competitive",
    status: "active",
  },
  {
    id: "vnd-havells",
    code: "VND-0004",
    name: "Havells Electrical Supplies",
    type: "Manufacturer",
    gstNumber: "07AABCH4321M1Z9",
    address: "Okhla Industrial Area, New Delhi",
    contacts: [
      { name: "Anita Desai", role: "Key Account Manager", phone: "+919811123456", email: "anita.desai@havells-example.com" },
    ],
    materialCategories: ["wires", "switches", "switchboards", "panel-boxes", "lights"],
    rating: 4.5,
    deliveryPerformance: 0.91,
    qualityAcceptanceRate: 0.97,
    rejectionRate: 0.03,
    priceCompetitiveness: "Premium",
    status: "active",
  },
  {
    id: "vnd-finolex",
    code: "VND-0005",
    name: "Finolex Pipes & Fittings",
    type: "Manufacturer",
    gstNumber: "27AAACF6789N1ZQ",
    address: "Ratnagiri, Maharashtra",
    contacts: [
      { name: "Suresh Naik", role: "Sales Executive", phone: "+919822233445", email: "suresh.naik@finolex-example.com" },
    ],
    materialCategories: ["upvc-pipes", "cpvc-pipes", "fittings", "valves"],
    rating: 4.4,
    deliveryPerformance: 0.88,
    qualityAcceptanceRate: 0.96,
    rejectionRate: 0.04,
    priceCompetitiveness: "Competitive",
    status: "active",
  },
  {
    id: "vnd-newage-fire",
    code: "VND-0006",
    name: "NewAge Fire Systems",
    type: "Supplier",
    gstNumber: "33AABCN7788P1ZR",
    address: "Ambattur Industrial Estate, Chennai, Tamil Nadu",
    contacts: [
      { name: "Ganesh Iyer", role: "Technical Director", phone: "+919444556677", email: "ganesh.iyer@newagefire-example.com" },
    ],
    materialCategories: ["fire-pipes", "fire-pumps", "sprinklers"],
    rating: 4.3,
    deliveryPerformance: 0.85,
    qualityAcceptanceRate: 0.95,
    rejectionRate: 0.05,
    priceCompetitiveness: "Competitive",
    status: "active",
  },
  {
    id: "vnd-kajaria",
    code: "VND-0007",
    name: "Kajaria Tiles Depot",
    type: "Distributor",
    gstNumber: "08AABCK3344Q1ZS",
    address: "Sitapura Industrial Area, Jaipur, Rajasthan",
    contacts: [
      { name: "Priya Menon", role: "Channel Partner", phone: "+919829011223", email: "priya.menon@kajaria-example.com" },
    ],
    materialCategories: ["tiles"],
    rating: 4.2,
    deliveryPerformance: 0.87,
    qualityAcceptanceRate: 0.94,
    rejectionRate: 0.06,
    priceCompetitiveness: "Competitive",
    status: "active",
  },
  {
    id: "vnd-asian-paints",
    code: "VND-0008",
    name: "Asian Paints Project Sales",
    type: "Manufacturer",
    gstNumber: "27AAACA5566R1ZT",
    address: "Turbhe, Navi Mumbai, Maharashtra",
    contacts: [
      { name: "Deepak Rao", role: "Project Sales Lead", phone: "+919820112233", email: "deepak.rao@asianpaints-example.com" },
    ],
    materialCategories: ["paint", "doors"],
    rating: 4.7,
    deliveryPerformance: 0.93,
    qualityAcceptanceRate: 0.98,
    rejectionRate: 0.02,
    priceCompetitiveness: "Premium",
    status: "active",
  },
  {
    id: "vnd-larsen-equip",
    code: "VND-0009",
    name: "Larsen Equipment Rentals",
    type: "Rental & Supply",
    gstNumber: "29AABCL2233S1ZU",
    address: "Whitefield, Bengaluru, Karnataka",
    contacts: [
      { name: "Farhan Sheikh", role: "Fleet Manager", phone: "+919980011223", email: "farhan.sheikh@larsenequip-example.com" },
    ],
    materialCategories: ["water-tankers", "machinery", "tools"],
    rating: 4.0,
    deliveryPerformance: 0.8,
    qualityAcceptanceRate: 0.9,
    rejectionRate: 0.1,
    priceCompetitiveness: "Value",
    status: "active",
  },
  {
    id: "vnd-crescent-brick",
    code: "VND-0010",
    name: "Crescent Brick Works",
    type: "Manufacturer",
    gstNumber: "36AABCC4455T1ZV",
    address: "Shamshabad, Hyderabad, Telangana",
    contacts: [
      { name: "Lakshmi Reddy", role: "Owner", phone: "+919885566778", email: "lakshmi.reddy@crescentbrick-example.com" },
    ],
    materialCategories: ["bricks"],
    rating: 3.9,
    deliveryPerformance: 0.78,
    qualityAcceptanceRate: 0.89,
    rejectionRate: 0.11,
    priceCompetitiveness: "Value",
    status: "under-review",
  },
  {
    id: "vnd-idigitronics",
    code: "VND-0011",
    name: "iDigritronics Semiconductors (I) Pvt Ltd",
    type: "Manufacturer",
    gstNumber: "36AADCI8740D1ZN",
    panNumber: "AADCI8740D",
    address: "H.No: 32-83/2, SN 14, Sainik Nagar, Ramakrishnapuram, Hyderabad, Telangana - 500056",
    contacts: [
      { name: "Sudarshan", role: "Vendor Contact", phone: "+91 9849304878", email: "Sudarshan.p@idigitronics.com" },
    ],
    materialCategories: ["electrical", "elv", "bms"],
    rating: 4.2,
    deliveryPerformance: 0.86,
    qualityAcceptanceRate: 0.94,
    rejectionRate: 0.06,
    priceCompetitiveness: "Competitive",
    status: "active",
  },
  {
    id: "vnd-kone-elevator",
    code: "VND-0012",
    name: "Kone Elevator India Pvt Ltd",
    type: "Manufacturer",
    gstNumber: "36AAACK2567P1Z2",
    panNumber: "AAACK2567P",
    address: "NH 65, Dharma Reddy Colony, Phase II, Hydernagar, KPHB Kukatpally, No.1-2-22, 7th Fl, PNR High Nest, Hyderabad, Telangana - 500085",
    contacts: [
      { name: "Shaik Arafath", role: "Vendor Contact", phone: "+91 9701631786", email: "shaik.arafath@kone.com" },
    ],
    materialCategories: ["vertical-transportation"],
    rating: 4.6,
    deliveryPerformance: 0.9,
    qualityAcceptanceRate: 0.97,
    rejectionRate: 0.03,
    priceCompetitiveness: "Premium",
    status: "active",
  },
  {
    id: "vnd-ankura-plumbings",
    code: "VND-0013",
    name: "ANKURA Plumbings",
    type: "Supplier",
    gstNumber: "36ACHFA5955F1ZA",
    panNumber: "ACHFA5955F",
    address: "Flat no.302, H.no 8-4-371/B47,48,49 SSD Vaishnavi Arcade, Saradha Nagar, Hyderabad, Telangana - 500038",
    contacts: [
      { name: "Amiya Nayak", role: "Vendor Contact", phone: "9618883969", email: "amiyanayak941@gmail.com" },
    ],
    materialCategories: ["plumbing", "sanitary", "kitchen-and-pantry"],
    rating: 4.1,
    deliveryPerformance: 0.84,
    qualityAcceptanceRate: 0.93,
    rejectionRate: 0.07,
    priceCompetitiveness: "Competitive",
    status: "active",
  },
  {
    id: "vnd-jvr-infra",
    code: "VND-0014",
    name: "JVR Infra",
    type: "Contractor",
    gstNumber: "36AAKFJ4446P1ZP",
    panNumber: "AAKFJ4446P",
    address: "16-31-4, Yerram Estates, 6th Phase, KPHB Colony, Hyderabad, Telangana",
    contacts: [
      { name: "JVR Infra", role: "Vendor Contact", phone: "9618181313", email: "Jvrinfra22@gmail.com" },
    ],
    materialCategories: ["civil", "earthwork", "external-development"],
    rating: 4.0,
    deliveryPerformance: 0.82,
    qualityAcceptanceRate: 0.92,
    rejectionRate: 0.08,
    priceCompetitiveness: "Value",
    status: "active",
  },
  {
    id: "vnd-savitru-engineering",
    code: "VND-0015",
    name: "Savitru Engineering Enterprises Pvt Ltd",
    type: "Supplier",
    gstNumber: "36AAQCS0461G1Z8",
    panNumber: "AAQCS0461G",
    address: "05-053/772, Rami Reddy Nagar, Phase-V, Entn. JeediMetla, Hyderabad, Telangana - 500085",
    contacts: [
      { name: "Savitru Engineering", role: "Vendor Contact", phone: "9908228660", email: "savitruengg@gmail.com" },
    ],
    materialCategories: ["fire-and-life-safety", "plumbing", "plant-and-equipment"],
    rating: 4.2,
    deliveryPerformance: 0.85,
    qualityAcceptanceRate: 0.94,
    rejectionRate: 0.06,
    priceCompetitiveness: "Competitive",
    status: "active",
  },
  {
    id: "vnd-kiran-godwin",
    code: "VND-0016",
    name: "Kiran - Godwin",
    type: "Supplier",
    gstNumber: "37AASFG4581G1ZX",
    panNumber: "AASFG4581G",
    address: "D/No. 3-1-150, B.R Ambedkar Road, Vijayawada, Andhra Pradesh - 520012",
    contacts: [
      { name: "Godwin", role: "Vendor Contact", phone: "7418759171", email: "godwinfps@gmail.com" },
    ],
    materialCategories: ["fire-and-life-safety", "site-setup"],
    rating: 4.0,
    deliveryPerformance: 0.82,
    qualityAcceptanceRate: 0.91,
    rejectionRate: 0.09,
    priceCompetitiveness: "Value",
    status: "active",
  },
  {
    id: "vnd-vibrant-facade",
    code: "VND-0017",
    name: "Vibrant Facade",
    type: "Supplier",
    gstNumber: "36AAMFV4689C1ZP",
    panNumber: "AAMFV4689C",
    address: "Plot No. 109/B, Survey No. 172, IDA Bollaram Industrial Area, Sangareddy district, Telangana - 502325",
    contacts: [
      { name: "Vibrant Facade", role: "Vendor Contact", phone: "9581951003", email: "vibrantfacadesllp@gmail.com" },
    ],
    materialCategories: ["facade", "doors-and-hardware"],
    rating: 4.3,
    deliveryPerformance: 0.87,
    qualityAcceptanceRate: 0.95,
    rejectionRate: 0.05,
    priceCompetitiveness: "Competitive",
    status: "active",
  },
  {
    id: "vnd-ravi-varma-cummins",
    code: "VND-0018",
    name: "Ravi Varma",
    type: "Service Partner",
    gstNumber: "NA",
    panNumber: "NA",
    address: "Srinivasa Engineers - Cummins Authorized Service Partner, Hyderabad, Telangana",
    contacts: [
      { name: "Ravi Varma", role: "Vendor Contact", phone: "8297563176", email: "NA" },
    ],
    materialCategories: ["plant-and-equipment", "electrical"],
    rating: 4.0,
    deliveryPerformance: 0.83,
    qualityAcceptanceRate: 0.92,
    rejectionRate: 0.08,
    priceCompetitiveness: "Competitive",
    status: "active",
  },
  {
    id: "vnd-sgs-security",
    code: "VND-0019",
    name: "Sarath - SGS Security Services",
    type: "Service Provider",
    gstNumber: "NA",
    panNumber: "NA",
    address: "35/A, Santoshi Southern, 1st Floor, Beside Sree Amoga Collage, SR Nagar, Hyderabad, Telangana - 500038",
    contacts: [
      { name: "Sarath", role: "Vendor Contact", phone: "9553737272", email: "sgsss.sales@gmail.com" },
    ],
    materialCategories: ["site-setup", "external-development"],
    rating: 4.1,
    deliveryPerformance: 0.84,
    qualityAcceptanceRate: 0.93,
    rejectionRate: 0.07,
    priceCompetitiveness: "Value",
    status: "active",
  },
];
export function getVendorById(vendorId) {
  return VENDORS.find((vendor) => vendor.id === vendorId) ?? null;
}
export function getVendorsForCategory(categoryId) {
  return VENDORS.filter((vendor) =>
    vendor.materialCategories.includes(categoryId),
  );
}
